// src/components/StoryLoader.vue
<template :key="loadingStatus">
  <div class="StoryLoader">

    <Story v-if="'succeeded' === loadingStatus"
      v-bind:title="title"
      v-bind:author="author"
      v-bind:text="text"
      v-bind:storyUrl="storyUrl"
     />

    <div v-if="'no-url' === loadingStatus">
      <input class="StoryLoader-url" v-model="storyUrl" placeholder="story URL" type="text" />
      <input class="StoryLoader-title" v-model="title" placeholder="story title" type="text" />
      <input class="StoryLoader-author" v-model="author" placeholder="story author" type="text" />
      <button class="StoryLoader-read-button" @click="onReadButtonClick">
        Read Story
      </button>
    </div>

    <p v-if="'loading' === loadingStatus">
      Loading...
    </p>

    <p v-if="'failed' === loadingStatus">
      Failed to load.
    </p>
  </div>
</template>


<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import { AxiosInstance } from 'axios';
import Story from '@/components/Story.vue';
import { getStorage } from '@/helpers';

@Component({
  components: {
    Story,
  }
})
export default class StoryLoader extends Vue {
  public static readonly PROXY_URL: string = 'https://cors-anywhere.herokuapp.com';

  @Prop() private readonly axios!: AxiosInstance;

  public title: string | null = null;
  public author: string | null = null;
  public text: string | null = null;
  public storyUrl: string | null = null;
  public loadingStatus: 'loading' | 'succeeded' | 'failed' | 'no-url' = 'no-url';

  private readonly storage: Storage = getStorage();

  private async created() {
    if (!this.storyUrl || !this.storage) return;

    const url = this.storyUrl;
    const storyText = this.storage.getItem(url) || await this.loadStory(url);
    this.updateStoryText(storyText);
  }

  private async onReadButtonClick() {
    if (!this.storyUrl) return;

    const storyText = await this.loadStory(this.storyUrl);
    this.updateStoryText(storyText);
  }

  private async loadStory(storyUrl: string): Promise<string | null> {
    this.loadingStatus = 'loading';
    try {
      const proxiedUrl = `${StoryLoader.PROXY_URL}/${storyUrl}`;
      const response = await this.axios.get(proxiedUrl);
      return response.data;
    } catch (error) {
      this.loadingStatus = 'failed';
      return null;
    }
  }

  private updateStoryText(storyText: string | null): void {
    if (!storyText) return;

    this.text = storyText;
    this.loadingStatus = 'succeeded';

    if (this.storyUrl) {
      this.storage.setItem(this.storyUrl, storyText);
    }
  }
}
</script>


<style lang="scss">
html, body {
  padding: 0;
  margin: 0;
}
</style>

// src/Story/StoryLoader.tsx
import React, { Component, ReactNode } from 'react';
import { MinimalAxios } from '../_support/MinimalAxios';
import StoryView, { Props as StoryProps } from './StoryView';
import { Story } from './Story';
import './StoryLoader.scss';

export enum LoadingStatus {
  Loading,
  Succeeded,
  Failed,
  MissingRequiredData,
}

export interface Props extends StoryProps {
  readonly axios: MinimalAxios;
}

export interface State {
  loadingStatus: LoadingStatus;
  story: Story;
}

class StoryLoader extends Component<Props, State> {
  public static readonly PROXY_URL: string = 'https://cors-anywhere.herokuapp.com';

  public state: State = {
    loadingStatus: (!!this.props.url) ? LoadingStatus.Loading : LoadingStatus.MissingRequiredData,
    story: this.defaultStoryState(),
  };

  private defaultStoryState(): Story {
    return { url: '', text: '', ...this.props };
  }

  constructor(props: Props) {
    super(props);
    this.updateStoryText = this.updateStoryText.bind(this);
    this.onInputChange = this.onInputChange.bind(this);
  }

  public componentDidMount() {
    this.updateStoryText();
  }

  public render() {
    return (
      <div className="StoryLoader">
        {this.renderContent()}
      </div>
    );
  }

  private renderContent(): ReactNode {
    switch (this.state.loadingStatus) {
      case LoadingStatus.MissingRequiredData:
        return this.renderForm();

      case LoadingStatus.Loading:
        return <p>Loading...</p>;

      case LoadingStatus.Failed:
        return <p>Failed to load.</p>;

      case LoadingStatus.Succeeded:
        return <StoryView {...this.state.story} storage={this.props.storage} />;

      default:
        return <p>Unknown error!</p>;
    }
  }

  private renderForm(): ReactNode {
    return (
      <React.Fragment>
        {this.renderInput('url')}
        {this.renderInput('title')}
        {this.renderInput('author')}

        <button
          className="StoryLoader-read-button"
          disabled={!this.state.story.url}
          onClick={this.updateStoryText}
        >
          Read Story
        </button>
      </React.Fragment>
    );
  }

  private renderInput(attr: keyof Story): ReactNode {
    return (
      <input
        className={`StoryLoader-${attr}`}
        placeholder={`story ${attr}`}
        name={attr}
        defaultValue={this.state.story[attr]}
        onChange={this.onInputChange}
      />
    );
  }

  private async updateStoryText() {
    if (!this.state.story.url) return;
    const storyUrl = this.state.story.url;

    this.setState({ loadingStatus: LoadingStatus.Loading }, async () => {

      let storyText = await this.props.storage.getItem<string>(storyUrl);

      if (!storyText) {
        try {
          const proxiedUrl = `${StoryLoader.PROXY_URL}/${storyUrl}`;
          const response = await this.props.axios.get(proxiedUrl);
          storyText = response.data;
        } catch (error) {
          return this.setState({ loadingStatus: LoadingStatus.Failed });
        }
      }

      if (!storyText) {
        return this.setState({ loadingStatus: LoadingStatus.Failed });
      }

      this.props.storage.setItem<string>(storyUrl, storyText);
      const story = this.state.story;
      story.text = storyText || '';
      this.setState({ story, loadingStatus: LoadingStatus.Succeeded });

    });
  }

  private onInputChange(event: any) {
    const target = event.target;
    const story = this.state.story;
    (story as any)[target.name] = target.value;
    this.setState({ story });
  }
}

export default StoryLoader;
