// src/components/Story.vue
<template>
  <div class="Story" v-resize.initial="onResize">

    <div class="Story-metadata" v-if="title && author">
        <span class="Story-title">{{ title }}</span>
        <span class="Story-author">{{ author }}</span>
        <vue-headful :title="title" />
    </div>
    <div class="Story-metadata" v-else>
        <span class="Story-url">{{ storyUrl }}</span>
        <vue-headful :title="storyUrl" />
    </div>

    <div class="Story-text-container" ref="storyTextContainer">
      <div class="Story-text" ref="storyText">
        <p v-html="$sanitize(text)"></p>
      </div>
      <div class="Story-fin">❧</div>
    </div>

    <div class="Story-pages-container">
      <span class="Story-pages">
        page
        <span class="Story-pages-current">{{ currentPage }}</span>
        of
        <span class="Story-pages-total">{{ totalPages }}</span>
      </span>
    </div>

  </div>
</template>


<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import resize from 'vue-resize-directive';
import { getStorage } from '@/helpers';

@Component({
  directives: { resize }
})
export default class Story extends Vue {
  public currentPage: number = 1;
  public totalPages: number = 0;

  @Prop() public readonly text!: string;
  @Prop() public readonly title!: string;
  @Prop() public readonly author!: string;
  @Prop() public readonly storyUrl!: string;

  private readonly storage: Storage;

  private DEFAULT_LINE_HEIGHT = '16px';

  constructor() {
    super();
    this.storage = getStorage();
  }

  public calculateTotalPages(
    visibleHeight: number,
    fullStoryTextHeight: number,
    lineHeight: number
  ): number {
    const totalLines = fullStoryTextHeight / lineHeight;
    const visibleLines = visibleHeight / lineHeight;

    const floatPages = totalLines / visibleLines;
    const integerPages = Math.floor(floatPages);
    const maybeExtraPage = (floatPages > integerPages ? 1 : 0);

    return integerPages + maybeExtraPage;
  }

  public calculateCurrentPage(scrollPosition: number, scrollHeight: number): number {
    const pageSize = scrollHeight / this.totalPages;
    const adjustedScrollPosition = scrollPosition + (pageSize / 2);
    const floatCurrentPage = adjustedScrollPosition / scrollHeight * this.totalPages;
    const integerCurrentPage = Math.floor(floatCurrentPage) + 1;
    return Math.min(Math.max(1, integerCurrentPage), this.totalPages);
  }

  private beforeMount() {
    window.addEventListener('scroll', this.onScroll);
  }

  private beforeDestroy() {
    window.removeEventListener('scroll', this.onScroll);
  }

  private mounted() {
    const savedScrollPosition = this.storage.getItem(`currentScrollPosition-${this.storyUrl}`);
    if (savedScrollPosition) {
      const position = parseInt(savedScrollPosition, 10);
      const options: ScrollToOptions = { top: position };
      window.scrollTo(options);
    }
  }

  private onResize(): void {
    this.updateTotalPages();
  }

  private onScroll(e: Event): void {
    this.updateCurrentPage();
    this.saveCurrentScrollPosition();
  }

  private updateTotalPages(): void {
    const storyTextEl = this.$refs.storyText as Element;
    const lineHeightStr = window.getComputedStyle(storyTextEl).lineHeight;
    const lineHeight = parseInt(lineHeightStr || this.DEFAULT_LINE_HEIGHT, 10);

    const totalPages = this.calculateTotalPages(
      window.innerHeight,
      storyTextEl.clientHeight,
      lineHeight
    );

    this.totalPages = totalPages;
  }

  private updateCurrentPage(): void {
    this.currentPage = this.calculateCurrentPage(
      window.scrollY, this.$el.scrollHeight
    );
  }

  private saveCurrentScrollPosition(): void {
    this.storage.setItem(
      `currentScrollPosition-${this.storyUrl}`,
      window.scrollY.toString()
    );
  }
}
</script>


<style lang="scss">
.Story {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

%Story-header-footer {
  background-color: #ccc;
  padding: 1em;
  display: flex;
}

.Story-metadata {
  @extend %Story-header-footer;
}

.Story-title {
  flex-grow: 1;
  font-weight: bold;
}

.Story-author {
  font-style: italic;
}

.Story-url {
  font-family: monospace;
  margin: 0 auto;
}

.Story-text-container {
  flex-grow: 1;
  padding: 0.5rem 1rem;
  background: linear-gradient(
    to bottom,
    #fbf6ed,
    #fbf6ed 50%,
    #efefef 50%,
    #efefef
  );
  background-size: 100% calc(2 * (100vh - 2rem));
}

.Story-text {
  max-width: 27rem;
  margin: 0 auto;
  line-height: 1.3em;
  font-size: large;
}

.Story-pages-container {
  @extend %Story-header-footer;
  position: sticky;
  bottom: 0;
  font-size: 0.75rem;
  font-style: italic;
}

.Story-pages {
  margin: 0 auto;
}

.Story-pages-current {
  font-weight: bold;
}

.Story-fin {
  text-align: center;
}
</style>

// src/Story/Story.tsx
import React, { Component, ReactNode } from 'react';
import { HeadProvider, Title } from 'react-head';
import SanitizedHTML from 'react-sanitized-html';
import sanitizeHtml from 'sanitize-html';
import { MinimalLocalForage } from '../_support/MinimalLocalForage';
import './Story.scss';

export interface Props {
  text: string;
  title?: string;
  author?: string;
  url?: string;
  readonly storage: MinimalLocalForage;
}

interface State {
  currentPage: number;
  totalPages: number;
}

class Story extends Component<Readonly<Props>, State> {
  private static readonly DEFAULT_LINE_HEIGHT = '16px';

  public state: State = {
    currentPage: 1,
    totalPages: 0,
  };

  private storyTextEl: HTMLDivElement | null = null;

  private storageKey = `currentScrollPosition-${this.props.url}`;

  public async componentDidMount() {
    this.setTotalPages();

    const savedScrollPosition = await this.props.storage.getItem<number>(this.storageKey);
    if (savedScrollPosition) {
      const options: ScrollToOptions = { top: savedScrollPosition };
      window.scrollTo(options);
    }

    window.addEventListener('resize', this.setTotalPages);
    window.addEventListener('scroll', this.setCurrentPage);
  }

  public componentWillUnmount() {
    window.removeEventListener('resize', this.setTotalPages);
    window.removeEventListener('scroll', this.setCurrentPage);
  }

  public render() {
    return (

      <div className="Story">

        <HeadProvider>
          <Title>{this.htmlTitle()}</Title>
        </HeadProvider>

        <div className="Story-metadata">
          {this.renderMetadata()}
        </div>

        <div className="Story-text-container">
          {this.renderText()}
        </div>

        <div className="Story-pages-container">
          {this.renderPageCounts()}
        </div>

      </div>

    );
  }

  private renderMetadata(): ReactNode {
    if (this.props.title && this.props.author) {
      return (
        <React.Fragment>
          <span className="Story-title">{this.props.title}</span>
          <span className="Story-author">{this.props.author}</span>
        </React.Fragment>
      );
    }

    return <span className="Story-url">{this.props.url}</span>;
  }

  private renderText(): ReactNode {
    const allowedTags = sanitizeHtml.defaults.allowedTags.concat([
      'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    ]);

    return (
      <React.Fragment>

        <div
          className="Story-text"
          ref={(el) => { this.storyTextEl = el; }}
        >
          <SanitizedHTML
            allowedTags={allowedTags}
            html={this.props.text}
          />
        </div>

        <div className="Story-fin">❧</div>
      </React.Fragment>
    );
  }

  private renderPageCounts(): ReactNode {
    // Shenanigans to preserve space between the rendered words.
    const page = <span>page</span>;
    const current = <span className="Story-pages-current">{this.state.currentPage}</span>;
    const of = <span>of</span>;
    const total = <span className="Story-pages-total">{this.state.totalPages}</span>;

    return (
      <span className="Story-pages">
        {page} {current} {of} {total}
      </span>
    );
  }

  private htmlTitle(): string {
    let title: string;
    if (this.props.title && this.props.author) {
      title = `${this.props.title} — ${this.props.author}`;
    } else {
      title = this.props.url || '';
    }
    return `Colibri: ${title}`;
  }

  private setTotalPages = (): void => {
    if (!this.storyTextEl) return;

    const storyTextStyle = window.getComputedStyle(this.storyTextEl);
    const lineHeightStr = storyTextStyle.lineHeight;
    const lineHeight = parseInt(lineHeightStr || Story.DEFAULT_LINE_HEIGHT, 10);

    const totalPages = this.calculateTotalPages(
      window.innerHeight,
      this.storyTextEl.clientHeight,
      lineHeight
    );

    if (totalPages !== this.state.totalPages) {
      this.setState({ totalPages });
    }
  }

  public calculateTotalPages(
    visibleHeight: number,
    fullStoryTextHeight: number,
    lineHeight: number
  ): number {
    const totalLines = fullStoryTextHeight / lineHeight;
    const visibleLines = visibleHeight / lineHeight;

    const floatPages = totalLines / visibleLines;
    const integerPages = Math.floor(floatPages);
    const maybeExtraPage = (floatPages > integerPages ? 1 : 0);

    return integerPages + maybeExtraPage;
  }

  private setCurrentPage = (): void => {
    if (!this.storyTextEl) return;

    this.props.storage.setItem<number>(this.storageKey, window.scrollY);

    const currentPage = this.calculateCurrentPage(
      window.scrollY,
      this.storyTextEl.scrollHeight
    );

    if (currentPage !== this.state.currentPage) {
      this.setState({ currentPage });
    }
  }

  public calculateCurrentPage(scrollPosition: number, scrollHeight: number): number {
    const pageSize = scrollHeight / this.state.totalPages;
    const adjustedScrollPosition = scrollPosition + (pageSize / 2);
    const floatCurrentPage = adjustedScrollPosition / scrollHeight * this.state.totalPages;
    const integerCurrentPage = Math.floor(floatCurrentPage) + 1;
    return Math.min(Math.max(1, integerCurrentPage), this.state.totalPages);
  }
}

export default Story;
